### PR TITLE
BUG FIX get_attached_modules() should only see modules attached in whole.

### LINKED ISSUE #87: [LINT_BUG]: Module linter not properly reading short path/module
### box.linters version

0.9.0

### Sample source code to lint

```R
box::use(
  shiny[testServer],
  testthat[expect_true, test_that],
)
box::use(
  app/main[server],
)

test_that("main server works", {
  testServer(server, {
    expect_true(grepl(x = output$message$html, pattern = "Check out Rhino docs!"))
  })
})
```

### Lint command used

```R
lintr::lint("tests/testthat/test-main.R", linters = box.linters::box_unused_attached_mod_linter())
```

### Lint result

```
Error: Linter 'box.linters::box_unused_attached_mod_linter' failed in /Users/radbasa/_dev/appsilon/rhino/tests/e2e/Rhinoapp/tests/testthat/test-main.R: invalid subscript type 'list'
```

### Expected result

This should not lint

### PR DESCRIPTION
**Pull request by radbasa**
Closes #87 

## Description
* Added extra explicit path to the XML Xpath query to properly identify modules attached in whole
* Added unit tests to handle `path/module` in addition to existing `path/to/module`
* Refer to #87 for bug description

## Definition of Done
- [ ] The change is thoroughly documented.
- [ ] The CI passes (`R CMD check`, linter, unit tests, spelling).
- [ ] Any generated files have been updated (e.g. `.Rd` files with `roxygen2::roxygenise()`)

### CODE REVIEW

File: tests/testthat/test-box_module_usage_halper_functions.R [hunk 1]
```diff
@@ -101,6 +101,108 @@ test_that("get_attached_modules does not return aliased functions", {
   expect_setequal(results$nested$module_b, module_b_objects)
 })
 
+
+#### Test different path structure
+options(box.path = file.path(getwd(), "mod", "path"))
```
Comment (jakubnowicki) [inline tests/testthat/test-box_module_usage_halper_functions.R:106]: Instead, I would suggest using `withr::with_option`, to be sure that the option change is only local. IMO this could also improve readability.

Comment (radbasa) [reply tests/testthat/test-box_module_usage_halper_functions.R]: Done.

**Review by jakubnowicki — APPROVED** [review]
